custom-objects {
    url-pattern {
        SOCIAL-SITES {
            value [ *.facebook.com *.instagram.com *.twitter.com ];
        }
        STREAM-SITES {
            value [ *.youtube.com *.netflix.com ];
        }
    }
    custom-url-category {
        BLOCKED-SOCIAL {
            value SOCIAL-SITES;
        }
        BLOCKED-STREAMING {
            value STREAM-SITES;
        }
    }
}
feature-profile {
    web-filtering {
        type juniper-enhanced;
        juniper-enhanced {
            profile EWF-BLOCK {
                category {
                    BLOCKED-SOCIAL {
                        action block;
                    }
                    BLOCKED-STREAMING {
                        action block;
                    }
                }
                default permit;
                fallback-settings {
                    default log-and-permit;
                    server-connectivity log-and-permit;
                    timeout log-and-permit;
                    too-many-requests log-and-permit;
                }
            }
        }
    }
}
utm-policy UTM-WEB {
    web-filtering {
        http-profile EWF-BLOCK;
    }
}
policy default-permit {
    match {
        source-address any;
        destination-address any;
        application any;
    }
    then {
        permit {
            application-services {
                utm-policy UTM-WEB;
            }
        }
    }
}
static {
    route 192.168.10.0/30 next-hop 10.0.0.1;
}
